src/Entity/Lesson.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LessonRepository")
 */
class Lesson
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="time")
     */
    private $time;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $location;

    /**
     * @ORM\Column(type="integer")
     */
    private $max_persons;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Training", inversedBy="lesson")
     */
    private $training;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Registration", mappedBy="lesson")
     */
    private $registration;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Person", inversedBy="lessons")
     */
    private $person;

    public function __construct()
    {
        $this->registration = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTime(): ?\DateTimeInterface
    {
        return $this->time;
    }

    public function setTime(\DateTimeInterface $time): self
    {
        $this->time = $time;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getMaxPersons(): ?int
    {
        return $this->max_persons;
    }

    public function setMaxPersons(int $max_persons): self
    {
        $this->max_persons = $max_persons;

        return $this;
    }

    public function getTraining(): ?Training
    {
        return $this->training;
    }

    public function setTraining(?Training $training): self
    {
        $this->training = $training;

        return $this;
    }

    /**
     * @return Collection|registration[]
     */
    public function getRegistration(): Collection
    {
        return $this->registration;
    }

    public function addRegistration(registration $registration): self
    {
        if (!$this->registration->contains($registration)) {
            $this->registration[] = $registration;
            $registration->setLesson($this);
        }

        return $this;
    }

    public function removeRegistration(registration $registration): self
    {
        if ($this->registration->contains($registration)) {
            $this->registration->removeElement($registration);
            // set the owning side to null (unless already changed)
            if ($registration->getLesson() === $this) {
                $registration->setLesson(null);
            }
        }

        return $this;
    }

    public function getPerson(): ?person
    {
        return $this->person;
    }

    public function setPerson(?person $person): self
    {
        $this->person = $person;

        return $this;
    }
}

src/Entity/Person.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;




/**
 * @ORM\Entity(repositoryClass="App\Repository\PersonRepository")
 * @UniqueEntity(fields={"username"}, message="There is already an account with this username")
 */
class Person implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $preprovision;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastname;

    /**
     * @ORM\Column(type="date")
     */
    private $dateofbirth;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $gender;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $emailaddress;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $hiring_date;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2, nullable=true)
     */
    private $salary;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $street;

    /**
     * @ORM\Column(type="string", length=6, nullable=true)
     */
    private $postal_code;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $place;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Lesson", mappedBy="person")
     */
    private $lessons;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Registration", mappedBy="person")
     */
    private $registrations;


    public function __construct()
    {
        $this->lessons = new ArrayCollection();
        $this->registrations = new ArrayCollection();
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';


        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getPreprovision(): ?string
    {
        return $this->preprovision;
    }

    public function setPreprovision(?string $preprovision): self
    {
        $this->preprovision = $preprovision;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getDateofbirth(): ?\DateTimeInterface
    {
        return $this->dateofbirth;
    }

    public function setDateofbirth(\DateTimeInterface $dateofbirth): self
    {
        $this->dateofbirth = $dateofbirth;

        return $this;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(string $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getEmailaddress(): ?string
    {
        return $this->emailaddress;
    }

    public function setEmailaddress(string $emailaddress): self
    {
        $this->emailaddress = $emailaddress;

        return $this;
    }

    public function getHiringDate(): ?\DateTimeInterface
    {
        return $this->hiring_date;
    }

    public function setHiringDate(?\DateTimeInterface $hiring_date): self
    {
        $this->hiring_date = $hiring_date;

        return $this;
    }

    public function getSalary(): ?string
    {
        return $this->salary;
    }

    public function setSalary(?string $salary): self
    {
        $this->salary = $salary;

        return $this;
    }

    public function getStreet(): ?string
    {
        return $this->street;
    }

    public function setStreet(?string $street): self
    {
        $this->street = $street;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(?string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getPlace(): ?string
    {
        return $this->place;
    }

    public function setPlace(?string $place): self
    {
        $this->place = $place;

        return $this;
    }
    /**
     * @return Collection|Lesson[]
     */
    public function getLessons(): Collection
    {
        return $this->lessons;
    }

    public function addLesson(Lesson $lesson): self
    {
        if (!$this->lessons->contains($lesson)) {
            $this->lessons[] = $lesson;
            $lesson->setPerson($this);
        }

        return $this;
    }

    public function removeLesson(Lesson $lesson): self
    {
        if ($this->lessons->contains($lesson)) {
            $this->lessons->removeElement($lesson);
            // set the owning side to null (unless already changed)
            if ($lesson->getPerson() === $this) {
                $lesson->setPerson(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Registration[]
     */
    public function getRegistrations(): Collection
    {
        return $this->registrations;
    }

    public function addRegistration(Registration $registration): self
    {
        if (!$this->registrations->contains($registration)) {
            $this->registrations[] = $registration;
            $registration->setPerson($this);
        }

        return $this;
    }

    public function removeRegistration(Registration $registration): self
    {
        if ($this->registrations->contains($registration)) {
            $this->registrations->removeElement($registration);
            // set the owning side to null (unless already changed)
            if ($registration->getPerson() === $this) {
                $registration->setPerson(null);
            }
        }

        return $this;
    }
}

src/Controller/MemberController.php
<?php


namespace App\Controller;


use App\Entity\Lesson;
use App\Entity\Person;
use App\Entity\Registration;
use App\Form\UserAccountFormType;
use App\Repository\LessonRepository;
use App\Repository\PersonRepository;
use App\Repository\RegistrationRepository;
use App\Repository\TrainingRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class MemberController extends AbstractController
{
    /**
     * @Route("member", name="app_member_homepage")
     */
    public function homepageAction()
    {
        Return $this->render("member/homepage.html.twig");
    }

    /**
     * @Route("member/gegevens", name="app_member_gegevens")
     */
    public function gegevensAction(PersonRepository $personRepository)
    {
        $em = $this->getDoctrine()->getManager();
        $user = $em->getRepository(Person::class)->find($this->getUser()->getId());

        return $this->render("member/gegevens.html.twig", [
            'person' => $personRepository->find($user)
        ]);
    }

    /**
     * @Route("member/gegevens/edit/{password}", name="app_member_gegevens_aanpassen")
     */
    public function gegevensEditAction(Request $request, $password, UserPasswordEncoderInterface $passwordEncoder)
    {
        $em = $this->getDoctrine()->getManager();
        $user = $em->getRepository(Person::class)->find($this->getUser()->getId());

        if ($password == "true") {
            $form = $this->createFormBuilder()
                ->add('password', PasswordType::class, array(
                    'mapped' => false,
                    'label' => 'Huidig wachtwoord'
                ))
                ->add('plainPassword', PasswordType::class, array(
                    'mapped' => false,
                    'label' => 'Nieuw wachtwoord'
                ))
//                ->add()
//                ->add()
//                ->add()
                ->getForm();
        } else {
            $form = $this->createForm(UserAccountFormType::class, $user);
        }
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            if ($passwordEncoder->isPasswordValid($this->getUser(), $form->get('password')->getData())) {
                if ($password == "true") {
                    $user->setPassword($passwordEncoder->encodePassword(
                        $user,
                        $form['plainPassword']->getData()
                    ));
                } else {
                    $user = $form->getData();
                }

                $em->persist($user);
                $em->flush();
                $this->addFlash("success", "Aanpassing is gelukt!");
                return $this->redirectToRoute('app_member_gegevens');

            } else {
                $this->addFlash("danger", "Wachtwoord is incorrect");
            }
        }
        return $this->render('member/gegevensAanpassen.html.twig', [
            'registrationForm' => $form->createView(),
        ]);
    }

    /**
     * @Route("member/les-inschrijving", name="app_member_lessen")
     */
    public function lessenAction(TrainingRepository $trainingRepository, LessonRepository $lessonRepository)
    {
        return $this->render("member/lessen.html.twig", [
            'trainingen' => $trainingRepository->findAll(),
            'lessons' => $lessonRepository->findAll()
        ]);
    }

    /**
     * @Route("member/lessen/aanmelden/{id}", name="app_member_les_aanmelden")
     */
    public function lesAanmeldingAction($id, PersonRepository $personRepository, LessonRepository $lessonRepository)
    {
        $em = $this->getDoctrine()->getManager();
        $user = $em->getRepository(Person::class)->find($this->getUser()->getId());
        $lesson = $em->getRepository(Lesson::class)->find($id);

        $registrations = $lesson->getRegistration();

        foreach ($registrations as $registration) {
            if ($registration->getPerson()->getId() == $this->getUser()->getId()) {
                $this->addFlash('danger', 'U heeft zich al aangemeld voor deze les');
                return $this->redirectToRoute('app_member_lessen');
            }
        }

        $registration = new Registration();
        $registration->setPerson($user);
        $registration->setLesson($lesson);

        $em->persist($registration);
        $em->flush();

        $this->addFlash('success', 'Registratie voltooid');

        return $this->redirectToRoute('app_member_persoon_lessen');

    }

    /**
     * @Route("member/trainingen", name="app_member_persoon_lessen")
     */
    public function persoonLessenAction(RegistrationRepository $registrationRepository)
    {
        return $this->render("member/persoonlessen.html.twig", [
            'registrations' => $registrationRepository->findAll(),
        ]);
    }

    /**
     * @Route("/member/training-delete/{id}", name="app_member_registratie_delete")
     */
    public function lessonDeleteAction($id)
    {

        $em = $this->getDoctrine()->getManager();
        $registration = $em->getRepository(Registration::class)->find($id);

        $em->remove($registration);
        $em->flush();
        $this->addFlash("success", "Registratie verwijderd");

        return $this->redirectToRoute('app_member_persoon_lessen');
    }
}

templates/member/gegevens.html.twig
{% extends 'member.html.twig' %}
{% block content %}
    <div class="col-4 m-5">
        <table class="table table-borderless mt-5">
            <tbody>
            <tr class="table-active">
                <th>Email</th>
                <td>{{ person.emailaddress }}</td>
            </tr>
            <tr class="table-active">
                <th>Password</th>
                <td><a href="{{ path('app_member_gegevens_aanpassen', {password: 'true'}) }}"><button class="btn btn-dark">Nieuw wachtwoord</button></a></td>
            </tr>
            <tr class="table-active">
                <th>Volledige naam</th>
                <td>{{ person.firstname }}
                    {{ person.preprovision }}
                    {{ person.lastname }}</td>
            </tr>
            <tr class="table-active">
                <th>Geboorte Datum</th>
                <td>{{ person.dateofbirth|date('d-M-y') }}</td>
            </tr>
            <tr class="table-active">
                <th>Geslacht</th>
                <td>{{ person.gender }}</td>
            </tr>
            <tr class="table-active">
                <th>Straatnaam</th>
                <td>{{ person.street }}</td>
            </tr>
            <tr class="table-active">
                <th>Postcode</th>
                <td>{{ person.postalCode }}</td>
            </tr>
            <tr class="table-active">
                <th>Plaats</th>
                <td>{{ person.place }}</td>
            </tr>
            </tbody>
        </table>
        <a href="{{ path('app_member_gegevens_aanpassen', {password: 'false'})}}"><button class="btn btn-primary">Pas Aan</button></a>
    </div>
{% endblock %}

templates/member/gegevensAanpassen.html.twig
{% extends 'member.html.twig' %}
{%  block content %}
    <div class="col m-5">
        {{ form_start(registrationForm) }}
        {{ form_widget(registrationForm) }}


        <button class="btn btn-lg btn-primary btn-block mb-3 mt-5" type="submit">
            Pas aan
        </button>
        {{ form_end(registrationForm) }}
    </div>
{% endblock %}

templates/member/homepage.html.twig
{% extends "member.html.twig" %}
{%  block content %}


{% endblock %}

templates/member/lessen.html.twig
{% extends "member.html.twig" %}
{% block content %}
<div class="m-2 col-12">
    <h1 class="text-center">lessen</h1>
    <table class="table">
        <thead>
        <tr>
            <th>Activiteit</th>
            <th>Descriptie</th>
            <th>Datum</th>
            <th>Tijdstip</th>
            <th>Duratie</th>
            <th>Locatie</th>
            <th>Aantal Inschrijvingen</th>
            <th>Instructeur</th>
            <th>kosten</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for lesson in lessons %}
            <tr>
                <th>{{ lesson.training.naam }}</th>
                <td>{{ lesson.training.desciption }}</td>
                <td>{{ lesson.date|date("m-d-Y") }}</td>
                <td>{{ lesson.time|date("H:i") }}</td>
                <td>{{ lesson.training.duration|date("H:i") }}</td>
                <td>{{ lesson.location }}</td>
                <td>{{ lesson.maxPersons }}</td>
                <td>{{ lesson.person.firstname }}</td>
                <td>{{ lesson.training.costs }}</td>
                <td><a href="{{ path('app_member_les_aanmelden' ,{id: lesson.id}) }}"><button class="btn btn-primary">inschrijven</button></a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/member/persoonlessen.html.twig
{% extends 'member.html.twig' %}
{%  block content %}
    <div class="m-2 col-12">
    <h1 class="text-center">lessen</h1>
    <table class="table">
    <thead>
    <tr>
        <th>Activiteit</th>
        <th>Descriptie</th>
        <th>Datum</th>
        <th>Tijdstip</th>
        <th>Duratie</th>
        <th>Locatie</th>
        <th>Aantal Inschrijvingen</th>
        <th>Instructeur</th>
        <th>kosten</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    {% for registration in registrations %}
        <tr>
            <th>{{ registration.lesson.training.naam }}</th>
            <td>{{ registration.lesson.training.desciption }}</td>
            <td>{{ registration.lesson.date|date("m-d-Y") }}</td>
            <td>{{ registration.lesson.time|date("H:i") }}</td>
            <td>{{ registration.lesson.training.duration|date("H:i") }}</td>
            <td>{{ registration.lesson.location }}</td>
            <td>{{ registration.lesson.maxPersons }}</td>
            <td>{{ registration.lesson.person.firstname }}</td>
            <td>{{ registration.lesson.training.costs }}</td>
            <td><a href="{{ path('app_member_registratie_delete' ,{id: registration.id}) }}"><button class="btn btn-primary">Afmelden</button></a></td>
        </tr>
    {% endfor %}
    </tbody>
    </table>
    </div>
{% endblock %}